export * from './IBody';
export * from './IContent';
export * from './IEditorial';
export * from './IEntity';
export * from './ISlug';
export * from './ITags';
export * from './ITaxonomy';
export * from './ITranslatable';
export * from './IURLPath';