name: "Test-Build-PR"
on:
  pull_request:
    branches-ignore: # disabled. Remove `-ignore` in order to enable
      - master
    types:
      - opened
      - synchronize
      - reopened
jobs:
  all_in_one:
    name: "Full Run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node12x-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn build
        if: always()
      - run: echo "::set-output name=pull_number::$(jq --raw-output .pull_request.number)"
        id: pull_number
        if: always()
